### ISSUE TITLE
Some labels overlap

### ISSUE THREAD

**Issue by gorkang** [ndphillips/yarrr#25]
When plotting 3 IV interactions it is not uncommon that the IV labels overlap (and others...). 

I am attaching a reproducible example with an annotated .svg (in red and orange the conflictive areas) 
[BUG Yarrr.zip](https://github.com/ndphillips/yarrr/files/542444/BUG.Yarrr.zip)

Thanks!

**Comment by ndphillips** [comment]
@nuskcalb Thanks for the note! I can think of two ways to fix this

1) Set `cex.lab` to something smaller...like `cex.lab = .6`. This will reduce the size of the text on the xaxis.

2) Change the names in your dataframe to something shorter so that they'll fit in the plot.

If neither of those solutions work for you, can you suggest how you'd like the plot to deal with this? That would help me come up with a better solution, thanks!

**Comment by nuskcalb** [comment]
Thanks @ndphillips 

Those options could work, but sometimes a proper verbose properly sized variable name/level is either unavoidable or just ugly :)

I can think of at least two options. The first, just have an option to use a color-coded legend (as in the ggplot "equivalent" example attached). The other, when the number of characters is too high, maybe place the variable names in two rows (for the same IV). Something like:

Ahorro----------------------Ahorro
-------------No Ahorro---------------No ahorro

Does any of that make sense?

Thanks for the great work!

[Rplot - ggplot.svg.zip](https://github.com/ndphillips/yarrr/files/544089/Rplot.-.ggplot.svg.zip)
